# Generated by Django 6.0.4 on 2026-04-09 09:43

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('subjectId', models.CharField(max_length=100)),
                ('dueDate', models.CharField(max_length=100)),
                ('dueTime', models.CharField(blank=True, max_length=100, null=True)),
                ('totalMarks', models.CharField(blank=True, max_length=50, null=True)),
                ('marks', models.CharField(blank=True, max_length=50, null=True)),
                ('priority', models.CharField(blank=True, choices=[('low', 'low'), ('medium', 'medium'), ('high', 'high')], max_length=20, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('link', models.URLField(blank=True, max_length=500, null=True)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('subjectId', models.CharField(max_length=100)),
                ('examDate', models.CharField(max_length=100)),
                ('examTime', models.CharField(max_length=100)),
                ('duration', models.CharField(blank=True, max_length=100, null=True)),
                ('venue', models.CharField(blank=True, max_length=200, null=True)),
                ('marks', models.CharField(blank=True, max_length=50, null=True)),
                ('examType', models.CharField(choices=[('midterm', 'midterm'), ('final', 'final'), ('quiz', 'quiz'), ('practical', 'practical'), ('internal', 'internal')], max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('subjectId', models.CharField(max_length=100)),
                ('chapter', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('link', models.URLField(blank=True, max_length=500, null=True)),
                ('tags', models.CharField(blank=True, max_length=300, null=True)),
                ('dateUploaded', models.CharField(blank=True, max_length=100, null=True)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('semester', models.CharField(blank=True, max_length=100, null=True)),
                ('teacher', models.CharField(blank=True, max_length=200, null=True)),
                ('color', models.CharField(default='#6366f1', max_length=50)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='SyllabusTopic',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=100, primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=300)),
                ('subjectId', models.CharField(max_length=100)),
                ('unit', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('not-started', 'not-started'), ('in-progress', 'in-progress'), ('completed', 'completed')], max_length=50)),
                ('plannedDate', models.CharField(blank=True, max_length=100, null=True)),
                ('completionDate', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('progress', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
